/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ControladorPrincipal;
import java.awt.Font;

/**
 *
 * @author I5-9600K
 */
public class PanelVideos extends javax.swing.JPanel {

    ControladorPrincipal controladorPrincipal;

    /**
     * Creates new form panelVideos
     */
    public PanelVideos() {
        initComponents();
        controladorPrincipal = new ControladorPrincipal(this);
    }

    public void cargarVideos() {
        jTableVideos.setModel(controladorPrincipal.consultarVideos());
        jTableVideos.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 14));
        jTableVideos.setFont(new java.awt.Font("Tahoma", 0, 12));
        
    }

    public void cargarDetalleVideos() {
        jTableVideos.setModel(controladorPrincipal.consultarDetalleVideos());
        jTableVideos.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 14));
        jTableVideos.setFont(new java.awt.Font("Tahoma", 0, 12));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVideos = new javax.swing.JTable();
        jButtonVolverVideo = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(628, 384));

        jTableVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableVideos);

        jButtonVolverVideo.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVolverVideo)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolverVideo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVideos;
    // End of variables declaration//GEN-END:variables
}
